version: "3"

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    entrypoint: sh -c "dockerize -wait tcp://db:3306 -timeout 20s npm install && node index.js"
    container_name: node
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - node
      - db
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
